### ISSUE TITLE
Establish pattern for creating personalized development environment.

### ISSUE THREAD

**Issue by mikeymicrophone** [mikeymicrophone/commissulator#3]
Commissulator uses the gem rails-env-credentials to enable storage of auth tokens in per-environment encrypted files which are committed to the repo.  To decrypt a set of credentials, a master key for that environment would have to be shared (NOT via the repo).

It would, most likely, be plausible to share the development environment's key.  One reason for not doing so is that the data set of clients, deals, and agents is expected to be mirrored in both Commissulator and Follow Up Boss.  If that account was shared with 5 developers, then each one might have local agents and clients the others didn't have.  Those would be pushed to Follow Up Boss, and then the other developers would be accessing a FUB account that included data not in their local environments.  That might not cause any actual problems, and it might actually carry lots of benefits for expedient development, but at this juncture we're going to experiment with using separate development environments, mostly to see how well it will work.

Begin by copying the file config/environments/development.rb into a new file in that same directory (you could name it development-cire.rb or something such as that).  This can be committed to the repo although in the future it might be pertinent to use gitignore on such files.  You will then use rails-env-credentials to generate your credential file and its master key as described here.  https://github.com/sinsoku/rails-env-credentials#other-environments-support

Edit the credentials file so it looks like so.

```
aws:
  access_key_id: t
  secret_access_key: t

sending_email:
  username: commissulator.development
  password: t

follow_up_boss:
  api_key: t
  subdomain: t

google:
  client_id: t.apps.googleusercontent.com
  client_secret: t

contactually:
  application_id: t
  secret: t
  token: t

microsoft:
  application_id: t
  public_key: t
  secret: https://stackoverflow.com/questions/52881340/how-does-one-open-or-view-the-private-key-delivered-from-the-microsoft-applicati
  password: t

rollbar:
  access_token: t

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: t
```
